// flow-typed signature: 11f393d0f6178f251bcb38f40bae91bd
// flow-typed version: <<STUB>>/director_v^1.2.8/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'director'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'director' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'director/build/director' {
  declare module.exports: any;
}

declare module 'director/build/director.min' {
  declare module.exports: any;
}

declare module 'director/build/ender' {
  declare module.exports: any;
}

declare module 'director/examples/http' {
  declare module.exports: any;
}

declare module 'director/lib/director' {
  declare module.exports: any;
}

declare module 'director/lib/director/browser' {
  declare module.exports: any;
}

declare module 'director/lib/director/cli' {
  declare module.exports: any;
}

declare module 'director/lib/director/http/index' {
  declare module.exports: any;
}

declare module 'director/lib/director/http/methods' {
  declare module.exports: any;
}

declare module 'director/lib/director/http/responses' {
  declare module.exports: any;
}

declare module 'director/lib/director/router' {
  declare module.exports: any;
}

declare module 'director/test/browser/backend/backend' {
  declare module.exports: any;
}

declare module 'director/test/browser/helpers/api' {
  declare module.exports: any;
}

declare module 'director/test/browser/html5-routes-test' {
  declare module.exports: any;
}

declare module 'director/test/browser/routes-test' {
  declare module.exports: any;
}

declare module 'director/test/server/cli/dispatch-test' {
  declare module.exports: any;
}

declare module 'director/test/server/cli/mount-test' {
  declare module.exports: any;
}

declare module 'director/test/server/cli/path-test' {
  declare module.exports: any;
}

declare module 'director/test/server/core/dispatch-test' {
  declare module.exports: any;
}

declare module 'director/test/server/core/insert-test' {
  declare module.exports: any;
}

declare module 'director/test/server/core/mount-test' {
  declare module.exports: any;
}

declare module 'director/test/server/core/on-test' {
  declare module.exports: any;
}

declare module 'director/test/server/core/path-test' {
  declare module.exports: any;
}

declare module 'director/test/server/core/regifystring-test' {
  declare module.exports: any;
}

declare module 'director/test/server/helpers/index' {
  declare module.exports: any;
}

declare module 'director/test/server/helpers/macros' {
  declare module.exports: any;
}

declare module 'director/test/server/http/accept-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/attach-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/before-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/configure-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/http-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/methods-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/recursion-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/responses-test' {
  declare module.exports: any;
}

declare module 'director/test/server/http/stream-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'director/build/director.js' {
  declare module.exports: $Exports<'director/build/director'>;
}
declare module 'director/build/director.min.js' {
  declare module.exports: $Exports<'director/build/director.min'>;
}
declare module 'director/build/ender.js' {
  declare module.exports: $Exports<'director/build/ender'>;
}
declare module 'director/examples/http.js' {
  declare module.exports: $Exports<'director/examples/http'>;
}
declare module 'director/lib/director.js' {
  declare module.exports: $Exports<'director/lib/director'>;
}
declare module 'director/lib/director/browser.js' {
  declare module.exports: $Exports<'director/lib/director/browser'>;
}
declare module 'director/lib/director/cli.js' {
  declare module.exports: $Exports<'director/lib/director/cli'>;
}
declare module 'director/lib/director/http/index.js' {
  declare module.exports: $Exports<'director/lib/director/http/index'>;
}
declare module 'director/lib/director/http/methods.js' {
  declare module.exports: $Exports<'director/lib/director/http/methods'>;
}
declare module 'director/lib/director/http/responses.js' {
  declare module.exports: $Exports<'director/lib/director/http/responses'>;
}
declare module 'director/lib/director/router.js' {
  declare module.exports: $Exports<'director/lib/director/router'>;
}
declare module 'director/test/browser/backend/backend.js' {
  declare module.exports: $Exports<'director/test/browser/backend/backend'>;
}
declare module 'director/test/browser/helpers/api.js' {
  declare module.exports: $Exports<'director/test/browser/helpers/api'>;
}
declare module 'director/test/browser/html5-routes-test.js' {
  declare module.exports: $Exports<'director/test/browser/html5-routes-test'>;
}
declare module 'director/test/browser/routes-test.js' {
  declare module.exports: $Exports<'director/test/browser/routes-test'>;
}
declare module 'director/test/server/cli/dispatch-test.js' {
  declare module.exports: $Exports<'director/test/server/cli/dispatch-test'>;
}
declare module 'director/test/server/cli/mount-test.js' {
  declare module.exports: $Exports<'director/test/server/cli/mount-test'>;
}
declare module 'director/test/server/cli/path-test.js' {
  declare module.exports: $Exports<'director/test/server/cli/path-test'>;
}
declare module 'director/test/server/core/dispatch-test.js' {
  declare module.exports: $Exports<'director/test/server/core/dispatch-test'>;
}
declare module 'director/test/server/core/insert-test.js' {
  declare module.exports: $Exports<'director/test/server/core/insert-test'>;
}
declare module 'director/test/server/core/mount-test.js' {
  declare module.exports: $Exports<'director/test/server/core/mount-test'>;
}
declare module 'director/test/server/core/on-test.js' {
  declare module.exports: $Exports<'director/test/server/core/on-test'>;
}
declare module 'director/test/server/core/path-test.js' {
  declare module.exports: $Exports<'director/test/server/core/path-test'>;
}
declare module 'director/test/server/core/regifystring-test.js' {
  declare module.exports: $Exports<'director/test/server/core/regifystring-test'>;
}
declare module 'director/test/server/helpers/index.js' {
  declare module.exports: $Exports<'director/test/server/helpers/index'>;
}
declare module 'director/test/server/helpers/macros.js' {
  declare module.exports: $Exports<'director/test/server/helpers/macros'>;
}
declare module 'director/test/server/http/accept-test.js' {
  declare module.exports: $Exports<'director/test/server/http/accept-test'>;
}
declare module 'director/test/server/http/attach-test.js' {
  declare module.exports: $Exports<'director/test/server/http/attach-test'>;
}
declare module 'director/test/server/http/before-test.js' {
  declare module.exports: $Exports<'director/test/server/http/before-test'>;
}
declare module 'director/test/server/http/configure-test.js' {
  declare module.exports: $Exports<'director/test/server/http/configure-test'>;
}
declare module 'director/test/server/http/http-test.js' {
  declare module.exports: $Exports<'director/test/server/http/http-test'>;
}
declare module 'director/test/server/http/methods-test.js' {
  declare module.exports: $Exports<'director/test/server/http/methods-test'>;
}
declare module 'director/test/server/http/recursion-test.js' {
  declare module.exports: $Exports<'director/test/server/http/recursion-test'>;
}
declare module 'director/test/server/http/responses-test.js' {
  declare module.exports: $Exports<'director/test/server/http/responses-test'>;
}
declare module 'director/test/server/http/stream-test.js' {
  declare module.exports: $Exports<'director/test/server/http/stream-test'>;
}
