// flow-typed signature: cb64307ac0e11f536300cc4bc0e5cca3
// flow-typed version: <<STUB>>/inferno-mobx_v^5.3.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-mobx/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/index.cjs.min' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/index.dev.esm' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/index.esm' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/inferno-mobx' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/inferno-mobx.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-mobx/dist/index.cjs.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/index.cjs'>;
}
declare module 'inferno-mobx/dist/index.cjs.min.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/index.cjs.min'>;
}
declare module 'inferno-mobx/dist/index.dev.esm.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/index.dev.esm'>;
}
declare module 'inferno-mobx/dist/index.esm.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/index.esm'>;
}
declare module 'inferno-mobx/dist/inferno-mobx.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/inferno-mobx'>;
}
declare module 'inferno-mobx/dist/inferno-mobx.min.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/inferno-mobx.min'>;
}
declare module 'inferno-mobx/index' {
  declare module.exports: $Exports<'inferno-mobx'>;
}
declare module 'inferno-mobx/index.js' {
  declare module.exports: $Exports<'inferno-mobx'>;
}
