// flow-typed signature: b1f5d516ff6b35652323548cc1486547
// flow-typed version: <<STUB>>/inferno-compat_v^5.3.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-compat/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/index.cjs.min' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/index.dev.esm' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/index.esm' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/inferno-compat' {
  declare module.exports: any;
}

declare module 'inferno-compat/dist/inferno-compat.min' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventConstants' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventPluginHub' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventPluginUtils' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/EventPropagators' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactCSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactFragment' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactMount' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/shallowCompare' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/SyntheticUIEvent' {
  declare module.exports: any;
}

declare module 'inferno-compat/lib/ViewportMetrics' {
  declare module.exports: any;
}

declare module 'inferno-compat/prop-types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-compat/dist/index.cjs.js' {
  declare module.exports: $Exports<'inferno-compat/dist/index.cjs'>;
}
declare module 'inferno-compat/dist/index.cjs.min.js' {
  declare module.exports: $Exports<'inferno-compat/dist/index.cjs.min'>;
}
declare module 'inferno-compat/dist/index.dev.esm.js' {
  declare module.exports: $Exports<'inferno-compat/dist/index.dev.esm'>;
}
declare module 'inferno-compat/dist/index.esm.js' {
  declare module.exports: $Exports<'inferno-compat/dist/index.esm'>;
}
declare module 'inferno-compat/dist/inferno-compat.js' {
  declare module.exports: $Exports<'inferno-compat/dist/inferno-compat'>;
}
declare module 'inferno-compat/dist/inferno-compat.min.js' {
  declare module.exports: $Exports<'inferno-compat/dist/inferno-compat.min'>;
}
declare module 'inferno-compat/index' {
  declare module.exports: $Exports<'inferno-compat'>;
}
declare module 'inferno-compat/index.js' {
  declare module.exports: $Exports<'inferno-compat'>;
}
declare module 'inferno-compat/lib/EventConstants.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventConstants'>;
}
declare module 'inferno-compat/lib/EventPluginHub.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventPluginHub'>;
}
declare module 'inferno-compat/lib/EventPluginUtils.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventPluginUtils'>;
}
declare module 'inferno-compat/lib/EventPropagators.js' {
  declare module.exports: $Exports<'inferno-compat/lib/EventPropagators'>;
}
declare module 'inferno-compat/lib/ReactCSSTransitionGroup.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactCSSTransitionGroup'>;
}
declare module 'inferno-compat/lib/ReactFragment.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactFragment'>;
}
declare module 'inferno-compat/lib/ReactMount.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactMount'>;
}
declare module 'inferno-compat/lib/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactTransitionEvents'>;
}
declare module 'inferno-compat/lib/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ReactTransitionGroup'>;
}
declare module 'inferno-compat/lib/shallowCompare.js' {
  declare module.exports: $Exports<'inferno-compat/lib/shallowCompare'>;
}
declare module 'inferno-compat/lib/SyntheticUIEvent.js' {
  declare module.exports: $Exports<'inferno-compat/lib/SyntheticUIEvent'>;
}
declare module 'inferno-compat/lib/ViewportMetrics.js' {
  declare module.exports: $Exports<'inferno-compat/lib/ViewportMetrics'>;
}
declare module 'inferno-compat/prop-types.js' {
  declare module.exports: $Exports<'inferno-compat/prop-types'>;
}
