// flow-typed signature: d7809098841919bf51a52b79a2c15284
// flow-typed version: <<STUB>>/inferno-mobx_v^3.7.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-mobx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-mobx/dist/index.es' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/index' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/inferno-mobx' {
  declare module.exports: any;
}

declare module 'inferno-mobx/dist/inferno-mobx.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-mobx/dist/index.es.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/index.es'>;
}
declare module 'inferno-mobx/dist/index.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/index'>;
}
declare module 'inferno-mobx/dist/inferno-mobx.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/inferno-mobx'>;
}
declare module 'inferno-mobx/dist/inferno-mobx.min.js' {
  declare module.exports: $Exports<'inferno-mobx/dist/inferno-mobx.min'>;
}
declare module 'inferno-mobx/index' {
  declare module.exports: $Exports<'inferno-mobx'>;
}
declare module 'inferno-mobx/index.js' {
  declare module.exports: $Exports<'inferno-mobx'>;
}
