// flow-typed signature: 3567da2538628fe01543a4d330b8802e
// flow-typed version: <<STUB>>/mobx-task_v^0.2.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-task'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-task' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-task/lib/index' {
  declare module.exports: any;
}

declare module 'mobx-task/lib/task' {
  declare module.exports: any;
}

declare module 'mobx-task/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-task/lib/index.js' {
  declare module.exports: $Exports<'mobx-task/lib/index'>;
}
declare module 'mobx-task/lib/task.js' {
  declare module.exports: $Exports<'mobx-task/lib/task'>;
}
declare module 'mobx-task/lib/utils.js' {
  declare module.exports: $Exports<'mobx-task/lib/utils'>;
}
