// flow-typed signature: 6d84dc3d0249b24cd393a6598a6de2bf
// flow-typed version: <<STUB>>/react-app-rewire-emotion_v^1.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-emotion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-emotion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-app-rewire-emotion/index' {
  declare module.exports: $Exports<'react-app-rewire-emotion'>;
}
declare module 'react-app-rewire-emotion/index.js' {
  declare module.exports: $Exports<'react-app-rewire-emotion'>;
}
