// flow-typed signature: b4b32d1bc2a218ff701c526d087e8da5
// flow-typed version: <<STUB>>/react-side-effect_v^1.1.5/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-side-effect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-side-effect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-side-effect/lib/index.es' {
  declare module.exports: any;
}

declare module 'react-side-effect/lib/index' {
  declare module.exports: any;
}

declare module 'react-side-effect/lib/index.umd' {
  declare module.exports: any;
}

declare module 'react-side-effect/lib/index.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-side-effect/lib/index.es.js' {
  declare module.exports: $Exports<'react-side-effect/lib/index.es'>;
}
declare module 'react-side-effect/lib/index.js' {
  declare module.exports: $Exports<'react-side-effect/lib/index'>;
}
declare module 'react-side-effect/lib/index.umd.js' {
  declare module.exports: $Exports<'react-side-effect/lib/index.umd'>;
}
declare module 'react-side-effect/lib/index.umd.min.js' {
  declare module.exports: $Exports<'react-side-effect/lib/index.umd.min'>;
}
