// flow-typed signature: 5c9304360dbf9aa5d4973659f176bd2a
// flow-typed version: <<STUB>>/ress_v^1.2.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ress' {
  declare module.exports: any;
}
